name: $(date:yyyyMMdd)$(rev:.r)

trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildNumber)'
  version: '1.21.6'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        containerRegistry: 'Dockerhub'
        repository: 'nginx'
        command: 'build'
        Dockerfile: '**/Dockerfile'
        tags: '$(tag)'
        arguments: '--build-arg NGINX_VERSION=$(version)'
    - task: Docker@2
      displayName: Push an image
      inputs:
        containerRegistry: 'Dockerhub'
        repository: 'nginx'
        command: 'push'
        tags: '$(tag)'
        arguments: '--build-arg NGINX_VERSION=$(version)'
