trigger:
- main

resources:
- repo: self

variables:
  tag: $(date:yyyyMMdd)$(rev:.r)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        containerRegistry: 'Dockerhub'
        repository: 'nginx'
        command: 'build'
        Dockerfile: '**/Dockerfile'
        tags: '$(tag)'
